runtime: nodejs14
instance_class: F2

handlers:
  - url: /static/js
    static_dir: build/static/js
    secure: always

  - url: /.*
    static_files: build/index.html
    upload: build/index.html

automatic_scaling:
  max_instances: 10
