steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud components install app-engine-python
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/arboreal-cat-381508/myportofolio', '.']

  # Push the Docker image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/arboreal-cat-381508/myportofolio']

  # Deploy the Docker image to App Engine
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      ['app', 'deploy', '--image-url=gcr.io/arboreal-cat-381508/myportofolio']
